export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_SEARCHED_LIST_REQUEST = "PRODUCT_SEARCHED_LIST_REQUEST";
export const PRODUCT_SEARCHED_LIST_SUCCESS = "PRODUCT_SEARCHED_LIST_SUCCESS";
export const PRODUCT_SEARCHED_LIST_FAIL = "PRODUCT_SEARCHED_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_EDIT_REVIEW_REQUEST = "PRODUCT_EDIT_REVIEW_REQUEST";
export const PRODUCT_EDIT_REVIEW_SUCCESS = "PRODUCT_EDIT_REVIEW_SUCCESS";
export const PRODUCT_EDIT_REVIEW_FAIL = "PRODUCT_EDIT_REVIEW_FAIL";